apiVersion: apps/v1
kind: Deployment
metadata:
  name: final-app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: final-app
  template:
    metadata:
      labels:
        app: final-app
    spec:
      containers:
        - name: final-app-container
          image: amirchapi/final-app:v1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5000
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "256Mi"
