apiVersion: v1
kind: Service
metadata:
  name: final-app-service
  labels:
    app: final-app
spec:
  selector:
    app: final-app
  ports:
    - port: 5000
      targetPort: 5000
      nodePort: 30080
  type: NodePort
